<script setup lang="ts">
import {
  ArrowUpRight,
  ArrowRight,
  ChevronRight,
  ChevronLeft,
  Search,
  Menu,
  X,
  Plus,
  Check,
  CalendarDays,
  Clock3,
  Heart,
  MapPin,
  Sparkles,
  Info,
  ChartNoAxesColumnIncreasing,
  LayoutGrid,
  Image,
  Smartphone,
  Coffee,
  BookOpen,
  PenLine,
  Palette,
  Code2,
  Copy,
  Mail,
  Github,
  ExternalLink,
  Maximize2,
  ArrowLeft,
  SlidersHorizontal,
  CheckCircle2,
  Layers,
  Sun,
  MoreHorizontal,
} from 'lucide-vue-next'
defineProps<{ name: string; size?: number }>()
const icons: Record<string, any> = {
  arrow: ArrowUpRight,
  right: ArrowRight,
  chevron: ChevronRight,
  previous: ChevronLeft,
  search: Search,
  menu: Menu,
  close: X,
  plus: Plus,
  check: Check,
  calendar: CalendarDays,
  clock: Clock3,
  heart: Heart,
  pin: MapPin,
  sparkles: Sparkles,
  info: Info,
  chart: ChartNoAxesColumnIncreasing,
  grid: LayoutGrid,
  image: Image,
  phone: Smartphone,
  coffee: Coffee,
  book: BookOpen,
  pen: PenLine,
  palette: Palette,
  code: Code2,
  copy: Copy,
  mail: Mail,
  github: Github,
  external: ExternalLink,
  expand: Maximize2,
  back: ArrowLeft,
  filter: SlidersHorizontal,
  success: CheckCircle2,
  layers: Layers,
  sun: Sun,
  more: MoreHorizontal,
}
</script>
<template>
  <component :is="icons[name] || Sparkles" :size="size || 20" :stroke-width="1.7" aria-hidden="true" />
</template>
